package com.main.pojo;
// Generated Oct 26, 2016 11:45:02 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblAccount generated by hbm2java
 */
@Entity
@Table(name="tbl_account"
    ,catalog="offsetmanager"
)
public class TblAccount  implements java.io.Serializable {


     private Integer AId;
     private TblClient tblClient;
     private TblOrder tblOrder;
     private TblQuotation tblQuotation;
     private String orderAmount;
     private String paidAmount;
     private String balanceAmount;

    public TblAccount() {
    }

    public TblAccount(TblClient tblClient, TblOrder tblOrder, TblQuotation tblQuotation, String orderAmount, String paidAmount, String balanceAmount) {
       this.tblClient = tblClient;
       this.tblOrder = tblOrder;
       this.tblQuotation = tblQuotation;
       this.orderAmount = orderAmount;
       this.paidAmount = paidAmount;
       this.balanceAmount = balanceAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="a_id", unique=true, nullable=false)
    public Integer getAId() {
        return this.AId;
    }
    
    public void setAId(Integer AId) {
        this.AId = AId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_id")
    public TblClient getTblClient() {
        return this.tblClient;
    }
    
    public void setTblClient(TblClient tblClient) {
        this.tblClient = tblClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="o_id")
    public TblOrder getTblOrder() {
        return this.tblOrder;
    }
    
    public void setTblOrder(TblOrder tblOrder) {
        this.tblOrder = tblOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="q_id")
    public TblQuotation getTblQuotation() {
        return this.tblQuotation;
    }
    
    public void setTblQuotation(TblQuotation tblQuotation) {
        this.tblQuotation = tblQuotation;
    }

    
    @Column(name="order_amount", length=20)
    public String getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount;
    }

    
    @Column(name="paid_amount", length=20)
    public String getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(String paidAmount) {
        this.paidAmount = paidAmount;
    }

    
    @Column(name="balance_amount", length=20)
    public String getBalanceAmount() {
        return this.balanceAmount;
    }
    
    public void setBalanceAmount(String balanceAmount) {
        this.balanceAmount = balanceAmount;
    }




}


