package com.main.pojo;
// Generated Oct 26, 2016 11:45:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblClient generated by hbm2java
 */
@Entity
@Table(name="tbl_client"
    ,catalog="offsetmanager"
)
public class TblClient  implements java.io.Serializable {


     private Integer CId;
     private String name;
     private Integer contact;
     private String emailId;
     private String city;
     private String shopName;
     private String officeAddress;
     private Set<TblQuotation> tblQuotations = new HashSet<TblQuotation>(0);
     private Set<TblAccount> tblAccounts = new HashSet<TblAccount>(0);
     private Set<TblParcel> tblParcels = new HashSet<TblParcel>(0);
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblClient() {
    }

    public TblClient(String name, Integer contact, String emailId, String city, String shopName, String officeAddress, Set<TblQuotation> tblQuotations, Set<TblAccount> tblAccounts, Set<TblParcel> tblParcels, Set<TblOrder> tblOrders) {
       this.name = name;
       this.contact = contact;
       this.emailId = emailId;
       this.city = city;
       this.shopName = shopName;
       this.officeAddress = officeAddress;
       this.tblQuotations = tblQuotations;
       this.tblAccounts = tblAccounts;
       this.tblParcels = tblParcels;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="c_id", unique=true, nullable=false)
    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="contact")
    public Integer getContact() {
        return this.contact;
    }
    
    public void setContact(Integer contact) {
        this.contact = contact;
    }

    
    @Column(name="email_id", length=20)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="city", length=20)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="shop_name", length=20)
    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    
    @Column(name="office_address", length=20)
    public String getOfficeAddress() {
        return this.officeAddress;
    }
    
    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblClient")
    public Set<TblQuotation> getTblQuotations() {
        return this.tblQuotations;
    }
    
    public void setTblQuotations(Set<TblQuotation> tblQuotations) {
        this.tblQuotations = tblQuotations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblClient")
    public Set<TblAccount> getTblAccounts() {
        return this.tblAccounts;
    }
    
    public void setTblAccounts(Set<TblAccount> tblAccounts) {
        this.tblAccounts = tblAccounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblClient")
    public Set<TblParcel> getTblParcels() {
        return this.tblParcels;
    }
    
    public void setTblParcels(Set<TblParcel> tblParcels) {
        this.tblParcels = tblParcels;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblClient")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


