package com.main.pojo;
// Generated Oct 26, 2016 11:45:02 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblGsmLup generated by hbm2java
 */
@Entity
@Table(name="tbl_gsm_lup"
    ,catalog="offsetmanager"
)
public class TblGsmLup  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Character isActive;

    public TblGsmLup() {
    }

    public TblGsmLup(String name, Character isActive) {
       this.name = name;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="isActive", length=1)
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }




}


