package com.main.pojo;
// Generated Oct 26, 2016 11:45:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblOrder generated by hbm2java
 */
@Entity
@Table(name="tbl_order"
    ,catalog="offsetmanager"
)
public class TblOrder  implements java.io.Serializable {


     private Integer OId;
     private TblClient tblClient;
     private TblQuotation tblQuotation;
     private String payment;
     private String orderPayment;
     private Set<TblParcel> tblParcels = new HashSet<TblParcel>(0);
     private Set<TblAccount> tblAccounts = new HashSet<TblAccount>(0);

    public TblOrder() {
    }

    public TblOrder(TblClient tblClient, TblQuotation tblQuotation, String payment, String orderPayment, Set<TblParcel> tblParcels, Set<TblAccount> tblAccounts) {
       this.tblClient = tblClient;
       this.tblQuotation = tblQuotation;
       this.payment = payment;
       this.orderPayment = orderPayment;
       this.tblParcels = tblParcels;
       this.tblAccounts = tblAccounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="o_id", unique=true, nullable=false)
    public Integer getOId() {
        return this.OId;
    }
    
    public void setOId(Integer OId) {
        this.OId = OId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_id")
    public TblClient getTblClient() {
        return this.tblClient;
    }
    
    public void setTblClient(TblClient tblClient) {
        this.tblClient = tblClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="q_id")
    public TblQuotation getTblQuotation() {
        return this.tblQuotation;
    }
    
    public void setTblQuotation(TblQuotation tblQuotation) {
        this.tblQuotation = tblQuotation;
    }

    
    @Column(name="payment", length=20)
    public String getPayment() {
        return this.payment;
    }
    
    public void setPayment(String payment) {
        this.payment = payment;
    }

    
    @Column(name="order_payment", length=20)
    public String getOrderPayment() {
        return this.orderPayment;
    }
    
    public void setOrderPayment(String orderPayment) {
        this.orderPayment = orderPayment;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblOrder")
    public Set<TblParcel> getTblParcels() {
        return this.tblParcels;
    }
    
    public void setTblParcels(Set<TblParcel> tblParcels) {
        this.tblParcels = tblParcels;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblOrder")
    public Set<TblAccount> getTblAccounts() {
        return this.tblAccounts;
    }
    
    public void setTblAccounts(Set<TblAccount> tblAccounts) {
        this.tblAccounts = tblAccounts;
    }




}


