package com.main.pojo;
// Generated Oct 26, 2016 11:45:02 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblParcel generated by hbm2java
 */
@Entity
@Table(name="tbl_parcel"
    ,catalog="offsetmanager"
)
public class TblParcel  implements java.io.Serializable {


     private Integer PId;
     private TblClient tblClient;
     private TblOrder tblOrder;
     private TblQuotation tblQuotation;
     private String fullPayment;
     private String balanceAmount;
     private String delivery;
     private String leftStock;
     private String deliveryDate;

    public TblParcel() {
    }

    public TblParcel(TblClient tblClient, TblOrder tblOrder, TblQuotation tblQuotation, String fullPayment, String balanceAmount, String delivery, String leftStock, String deliveryDate) {
       this.tblClient = tblClient;
       this.tblOrder = tblOrder;
       this.tblQuotation = tblQuotation;
       this.fullPayment = fullPayment;
       this.balanceAmount = balanceAmount;
       this.delivery = delivery;
       this.leftStock = leftStock;
       this.deliveryDate = deliveryDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="p_id", unique=true, nullable=false)
    public Integer getPId() {
        return this.PId;
    }
    
    public void setPId(Integer PId) {
        this.PId = PId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_id")
    public TblClient getTblClient() {
        return this.tblClient;
    }
    
    public void setTblClient(TblClient tblClient) {
        this.tblClient = tblClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="o_id")
    public TblOrder getTblOrder() {
        return this.tblOrder;
    }
    
    public void setTblOrder(TblOrder tblOrder) {
        this.tblOrder = tblOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="q_id")
    public TblQuotation getTblQuotation() {
        return this.tblQuotation;
    }
    
    public void setTblQuotation(TblQuotation tblQuotation) {
        this.tblQuotation = tblQuotation;
    }

    
    @Column(name="full_payment", length=20)
    public String getFullPayment() {
        return this.fullPayment;
    }
    
    public void setFullPayment(String fullPayment) {
        this.fullPayment = fullPayment;
    }

    
    @Column(name="balance_amount", length=20)
    public String getBalanceAmount() {
        return this.balanceAmount;
    }
    
    public void setBalanceAmount(String balanceAmount) {
        this.balanceAmount = balanceAmount;
    }

    
    @Column(name="delivery", length=20)
    public String getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(String delivery) {
        this.delivery = delivery;
    }

    
    @Column(name="left_stock", length=20)
    public String getLeftStock() {
        return this.leftStock;
    }
    
    public void setLeftStock(String leftStock) {
        this.leftStock = leftStock;
    }

    
    @Column(name="delivery_date", length=20)
    public String getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate;
    }




}


