package com.main.pojo;
// Generated Oct 26, 2016 11:45:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblQuotation generated by hbm2java
 */
@Entity
@Table(name="tbl_quotation"
    ,catalog="offsetmanager"
)
public class TblQuotation  implements java.io.Serializable {


     private Integer QId;
     private TblClient tblClient;
     private String quotationFor;
     private String paper;
     private String postPress;
     private String otherDesc;
     private Set<TblParcel> tblParcels = new HashSet<TblParcel>(0);
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);
     private Set<TblAccount> tblAccounts = new HashSet<TblAccount>(0);

    public TblQuotation() {
    }

    public TblQuotation(TblClient tblClient, String quotationFor, String paper, String postPress, String otherDesc, Set<TblParcel> tblParcels, Set<TblOrder> tblOrders, Set<TblAccount> tblAccounts) {
       this.tblClient = tblClient;
       this.quotationFor = quotationFor;
       this.paper = paper;
       this.postPress = postPress;
       this.otherDesc = otherDesc;
       this.tblParcels = tblParcels;
       this.tblOrders = tblOrders;
       this.tblAccounts = tblAccounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="q_id", unique=true, nullable=false)
    public Integer getQId() {
        return this.QId;
    }
    
    public void setQId(Integer QId) {
        this.QId = QId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="c_id")
    public TblClient getTblClient() {
        return this.tblClient;
    }
    
    public void setTblClient(TblClient tblClient) {
        this.tblClient = tblClient;
    }

    
    @Column(name="quotation_for", length=20)
    public String getQuotationFor() {
        return this.quotationFor;
    }
    
    public void setQuotationFor(String quotationFor) {
        this.quotationFor = quotationFor;
    }

    
    @Column(name="paper", length=20)
    public String getPaper() {
        return this.paper;
    }
    
    public void setPaper(String paper) {
        this.paper = paper;
    }

    
    @Column(name="post_press", length=20)
    public String getPostPress() {
        return this.postPress;
    }
    
    public void setPostPress(String postPress) {
        this.postPress = postPress;
    }

    
    @Column(name="other_desc", length=20)
    public String getOtherDesc() {
        return this.otherDesc;
    }
    
    public void setOtherDesc(String otherDesc) {
        this.otherDesc = otherDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblQuotation")
    public Set<TblParcel> getTblParcels() {
        return this.tblParcels;
    }
    
    public void setTblParcels(Set<TblParcel> tblParcels) {
        this.tblParcels = tblParcels;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblQuotation")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblQuotation")
    public Set<TblAccount> getTblAccounts() {
        return this.tblAccounts;
    }
    
    public void setTblAccounts(Set<TblAccount> tblAccounts) {
        this.tblAccounts = tblAccounts;
    }




}


