package com.main.pojo;
// Generated 4 Nov, 2016 4:39:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Offsetuser generated by hbm2java
 */
@Entity
@Table(name="offsetuser"
    ,catalog="offsetmanager"
)
public class Offsetuser  implements java.io.Serializable {


     private Integer adminId;
     private Integer userTypeId;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String emailId;
     private String lastLogin;
     private String actionPermission;
     private String pagePermission;
     private String intime;
     private String outtime;
     private String macid;
     private Character isActive;

    public Offsetuser() {
    }

    public Offsetuser(Integer userTypeId, String username, String password, String firstName, String lastName, String emailId, String lastLogin, String actionPermission, String pagePermission, String intime, String outtime, String macid, Character isActive) {
       this.userTypeId = userTypeId;
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.emailId = emailId;
       this.lastLogin = lastLogin;
       this.actionPermission = actionPermission;
       this.pagePermission = pagePermission;
       this.intime = intime;
       this.outtime = outtime;
       this.macid = macid;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="admin_id", unique=true, nullable=false)
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    
    @Column(name="user_type_id")
    public Integer getUserTypeId() {
        return this.userTypeId;
    }
    
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }

    
    @Column(name="username", length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="first_name", length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email_id", length=100)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="last_login", length=50)
    public String getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(String lastLogin) {
        this.lastLogin = lastLogin;
    }

    
    @Column(name="action_permission", length=100)
    public String getActionPermission() {
        return this.actionPermission;
    }
    
    public void setActionPermission(String actionPermission) {
        this.actionPermission = actionPermission;
    }

    
    @Column(name="page_permission", length=65535)
    public String getPagePermission() {
        return this.pagePermission;
    }
    
    public void setPagePermission(String pagePermission) {
        this.pagePermission = pagePermission;
    }

    
    @Column(name="intime", length=10)
    public String getIntime() {
        return this.intime;
    }
    
    public void setIntime(String intime) {
        this.intime = intime;
    }

    
    @Column(name="outtime", length=10)
    public String getOuttime() {
        return this.outtime;
    }
    
    public void setOuttime(String outtime) {
        this.outtime = outtime;
    }

    
    @Column(name="macid", length=50)
    public String getMacid() {
        return this.macid;
    }
    
    public void setMacid(String macid) {
        this.macid = macid;
    }

    
    @Column(name="is_active", length=1)
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }




}


