package com.main.pojo;
// Generated Nov 24, 2016 11:14:27 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAccount generated by hbm2java
 */
@Entity
@Table(name="tbl_account"
    ,catalog="offsetmanager"
)
public class TblAccount  implements java.io.Serializable {


     private Integer accountId;
     private TblClient tblClient;
     private TblOrder tblOrder;
     private Integer credited;
     private Integer debited;
     private Date accountAddedDate;
     private char isActive;

    public TblAccount() {
    }

	
    public TblAccount(Date accountAddedDate, char isActive) {
        this.accountAddedDate = accountAddedDate;
        this.isActive = isActive;
    }
    public TblAccount(TblClient tblClient, TblOrder tblOrder, Integer credited, Integer debited, Date accountAddedDate, char isActive) {
       this.tblClient = tblClient;
       this.tblOrder = tblOrder;
       this.credited = credited;
       this.debited = debited;
       this.accountAddedDate = accountAddedDate;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="account_id", unique=true, nullable=false)
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id")
    public TblClient getTblClient() {
        return this.tblClient;
    }
    
    public void setTblClient(TblClient tblClient) {
        this.tblClient = tblClient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id")
    public TblOrder getTblOrder() {
        return this.tblOrder;
    }
    
    public void setTblOrder(TblOrder tblOrder) {
        this.tblOrder = tblOrder;
    }

    
    @Column(name="credited")
    public Integer getCredited() {
        return this.credited;
    }
    
    public void setCredited(Integer credited) {
        this.credited = credited;
    }

    
    @Column(name="debited")
    public Integer getDebited() {
        return this.debited;
    }
    
    public void setDebited(Integer debited) {
        this.debited = debited;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="account_added_date", nullable=false, length=10)
    public Date getAccountAddedDate() {
        return this.accountAddedDate;
    }
    
    public void setAccountAddedDate(Date accountAddedDate) {
        this.accountAddedDate = accountAddedDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }




}


