package com.main.pojo;
// Generated 3 Nov, 2016 4:21:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblCardType generated by hbm2java
 */
@Entity
@Table(name="tbl_card_type"
    ,catalog="offsetmanager"
)
public class TblCardType  implements java.io.Serializable {


     private Integer cardTypeId;
     private String cardTypeName;
     private char isActive;
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblCardType() {
    }

	
    public TblCardType(String cardTypeName, char isActive) {
        this.cardTypeName = cardTypeName;
        this.isActive = isActive;
    }
    public TblCardType(String cardTypeName, char isActive, Set<TblOrder> tblOrders) {
       this.cardTypeName = cardTypeName;
       this.isActive = isActive;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="card_type_id", unique=true, nullable=false)
    public Integer getCardTypeId() {
        return this.cardTypeId;
    }
    
    public void setCardTypeId(Integer cardTypeId) {
        this.cardTypeId = cardTypeId;
    }

    
    @Column(name="card_type_name", nullable=false, length=30)
    public String getCardTypeName() {
        return this.cardTypeName;
    }
    
    public void setCardTypeName(String cardTypeName) {
        this.cardTypeName = cardTypeName;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblCardType")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


