package com.main.pojo;
// Generated 4 Nov, 2016 4:39:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblClient generated by hbm2java
 */
@Entity
@Table(name="tbl_client"
    ,catalog="offsetmanager"
)
public class TblClient  implements java.io.Serializable {


     private Integer clientId;
     private TblCitylist tblCitylist;
     private TblDistrict tblDistrict;
     private TblState tblState;
     private String clientName;
     private String clientAddress;
     private String propriterName;
     private String propriterImage;
     private String firmName;
     private String mobileNo;
     private String phoneNo1;
     private String postalAddress;
     private String phoneNo2;
     private Date clientAddedDate;
     private Date clientUpdateDate;
     private char isActive;
     private Set<TblQuotation> tblQuotations = new HashSet<TblQuotation>(0);
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblClient() {
    }

	
    public TblClient(String clientName, String clientAddress, String propriterName, String propriterImage, String firmName, String mobileNo, String phoneNo1, String postalAddress, String phoneNo2, Date clientAddedDate, Date clientUpdateDate, char isActive) {
        this.clientName = clientName;
        this.clientAddress = clientAddress;
        this.propriterName = propriterName;
        this.propriterImage = propriterImage;
        this.firmName = firmName;
        this.mobileNo = mobileNo;
        this.phoneNo1 = phoneNo1;
        this.postalAddress = postalAddress;
        this.phoneNo2 = phoneNo2;
        this.clientAddedDate = clientAddedDate;
        this.clientUpdateDate = clientUpdateDate;
        this.isActive = isActive;
    }
    public TblClient(TblCitylist tblCitylist, TblDistrict tblDistrict, TblState tblState, String clientName, String clientAddress, String propriterName, String propriterImage, String firmName, String mobileNo, String phoneNo1, String postalAddress, String phoneNo2, Date clientAddedDate, Date clientUpdateDate, char isActive, Set<TblQuotation> tblQuotations, Set<TblOrder> tblOrders) {
       this.tblCitylist = tblCitylist;
       this.tblDistrict = tblDistrict;
       this.tblState = tblState;
       this.clientName = clientName;
       this.clientAddress = clientAddress;
       this.propriterName = propriterName;
       this.propriterImage = propriterImage;
       this.firmName = firmName;
       this.mobileNo = mobileNo;
       this.phoneNo1 = phoneNo1;
       this.postalAddress = postalAddress;
       this.phoneNo2 = phoneNo2;
       this.clientAddedDate = clientAddedDate;
       this.clientUpdateDate = clientUpdateDate;
       this.isActive = isActive;
       this.tblQuotations = tblQuotations;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="client_id", unique=true, nullable=false)
    public Integer getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id")
    public TblCitylist getTblCitylist() {
        return this.tblCitylist;
    }
    
    public void setTblCitylist(TblCitylist tblCitylist) {
        this.tblCitylist = tblCitylist;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="district_id")
    public TblDistrict getTblDistrict() {
        return this.tblDistrict;
    }
    
    public void setTblDistrict(TblDistrict tblDistrict) {
        this.tblDistrict = tblDistrict;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="state_id")
    public TblState getTblState() {
        return this.tblState;
    }
    
    public void setTblState(TblState tblState) {
        this.tblState = tblState;
    }

    
    @Column(name="client_name", nullable=false, length=30)
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    
    @Column(name="client_address", nullable=false, length=65535)
    public String getClientAddress() {
        return this.clientAddress;
    }
    
    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress;
    }

    
    @Column(name="propriter_name", nullable=false, length=100)
    public String getPropriterName() {
        return this.propriterName;
    }
    
    public void setPropriterName(String propriterName) {
        this.propriterName = propriterName;
    }

    
    @Column(name="propriter_image", nullable=false, length=65535)
    public String getPropriterImage() {
        return this.propriterImage;
    }
    
    public void setPropriterImage(String propriterImage) {
        this.propriterImage = propriterImage;
    }

    
    @Column(name="firm_name", nullable=false, length=100)
    public String getFirmName() {
        return this.firmName;
    }
    
    public void setFirmName(String firmName) {
        this.firmName = firmName;
    }

    
    @Column(name="mobile_no", nullable=false, length=11)
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    
    @Column(name="phone_no_1", nullable=false, length=30)
    public String getPhoneNo1() {
        return this.phoneNo1;
    }
    
    public void setPhoneNo1(String phoneNo1) {
        this.phoneNo1 = phoneNo1;
    }

    
    @Column(name="postal_address", nullable=false, length=65535)
    public String getPostalAddress() {
        return this.postalAddress;
    }
    
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress;
    }

    
    @Column(name="phone_no_2", nullable=false, length=30)
    public String getPhoneNo2() {
        return this.phoneNo2;
    }
    
    public void setPhoneNo2(String phoneNo2) {
        this.phoneNo2 = phoneNo2;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="client_added_date", nullable=false, length=10)
    public Date getClientAddedDate() {
        return this.clientAddedDate;
    }
    
    public void setClientAddedDate(Date clientAddedDate) {
        this.clientAddedDate = clientAddedDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="client_update_date", nullable=false, length=10)
    public Date getClientUpdateDate() {
        return this.clientUpdateDate;
    }
    
    public void setClientUpdateDate(Date clientUpdateDate) {
        this.clientUpdateDate = clientUpdateDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblClient")
    public Set<TblQuotation> getTblQuotations() {
        return this.tblQuotations;
    }
    
    public void setTblQuotations(Set<TblQuotation> tblQuotations) {
        this.tblQuotations = tblQuotations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblClient")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


