package com.main.pojo;
// Generated Nov 24, 2016 11:14:27 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblDistrict generated by hbm2java
 */
@Entity
@Table(name="tbl_district"
    ,catalog="offsetmanager"
)
public class TblDistrict  implements java.io.Serializable {


     private Integer districtId;
     private String districtName;
     private String latitude;
     private String longitude;
     private String stateId;
     private char isActive;
     private Set<TblClient> tblClients = new HashSet<TblClient>(0);

    public TblDistrict() {
    }

	
    public TblDistrict(String stateId, char isActive) {
        this.stateId = stateId;
        this.isActive = isActive;
    }
    public TblDistrict(String districtName, String latitude, String longitude, String stateId, char isActive, Set<TblClient> tblClients) {
       this.districtName = districtName;
       this.latitude = latitude;
       this.longitude = longitude;
       this.stateId = stateId;
       this.isActive = isActive;
       this.tblClients = tblClients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="district_id", unique=true, nullable=false)
    public Integer getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    
    @Column(name="district_name", length=100)
    public String getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    
    @Column(name="latitude", length=10)
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", length=10)
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="state_id", nullable=false, length=50)
    public String getStateId() {
        return this.stateId;
    }
    
    public void setStateId(String stateId) {
        this.stateId = stateId;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblDistrict")
    public Set<TblClient> getTblClients() {
        return this.tblClients;
    }
    
    public void setTblClients(Set<TblClient> tblClients) {
        this.tblClients = tblClients;
    }




}


