package com.main.pojo;
// Generated Nov 26, 2016 10:29:34 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLamination generated by hbm2java
 */
@Entity
@Table(name="tbl_lamination"
    ,catalog="offsetmanager"
)
public class TblLamination  implements java.io.Serializable {


     private Integer laminationId;
     private String laminationName;
     private String laminationDesc;
     private Date laminationAddedDate;
     private char isActive;
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblLamination() {
    }

	
    public TblLamination(String laminationName, String laminationDesc, Date laminationAddedDate, char isActive) {
        this.laminationName = laminationName;
        this.laminationDesc = laminationDesc;
        this.laminationAddedDate = laminationAddedDate;
        this.isActive = isActive;
    }
    public TblLamination(String laminationName, String laminationDesc, Date laminationAddedDate, char isActive, Set<TblOrder> tblOrders) {
       this.laminationName = laminationName;
       this.laminationDesc = laminationDesc;
       this.laminationAddedDate = laminationAddedDate;
       this.isActive = isActive;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lamination_id", unique=true, nullable=false)
    public Integer getLaminationId() {
        return this.laminationId;
    }
    
    public void setLaminationId(Integer laminationId) {
        this.laminationId = laminationId;
    }

    
    @Column(name="lamination_name", nullable=false, length=100)
    public String getLaminationName() {
        return this.laminationName;
    }
    
    public void setLaminationName(String laminationName) {
        this.laminationName = laminationName;
    }

    
    @Column(name="lamination_desc", nullable=false, length=250)
    public String getLaminationDesc() {
        return this.laminationDesc;
    }
    
    public void setLaminationDesc(String laminationDesc) {
        this.laminationDesc = laminationDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lamination_added_date", nullable=false, length=10)
    public Date getLaminationAddedDate() {
        return this.laminationAddedDate;
    }
    
    public void setLaminationAddedDate(Date laminationAddedDate) {
        this.laminationAddedDate = laminationAddedDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="tblLamination")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


