package com.main.pojo;
// Generated 3 Nov, 2016 4:21:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblLaminationType generated by hbm2java
 */
@Entity
@Table(name="tbl_lamination_type"
    ,catalog="offsetmanager"
)
public class TblLaminationType  implements java.io.Serializable {


     private Integer laminationTypeId;
     private String laminationTypeName;
     private String laminationDesc;
     private Date laminationAddedDate;
     private char isActive;
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblLaminationType() {
    }

	
    public TblLaminationType(String laminationTypeName, String laminationDesc, Date laminationAddedDate, char isActive) {
        this.laminationTypeName = laminationTypeName;
        this.laminationDesc = laminationDesc;
        this.laminationAddedDate = laminationAddedDate;
        this.isActive = isActive;
    }
    public TblLaminationType(String laminationTypeName, String laminationDesc, Date laminationAddedDate, char isActive, Set<TblOrder> tblOrders) {
       this.laminationTypeName = laminationTypeName;
       this.laminationDesc = laminationDesc;
       this.laminationAddedDate = laminationAddedDate;
       this.isActive = isActive;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lamination_type_id", unique=true, nullable=false)
    public Integer getLaminationTypeId() {
        return this.laminationTypeId;
    }
    
    public void setLaminationTypeId(Integer laminationTypeId) {
        this.laminationTypeId = laminationTypeId;
    }

    
    @Column(name="lamination_type_name", nullable=false)
    public String getLaminationTypeName() {
        return this.laminationTypeName;
    }
    
    public void setLaminationTypeName(String laminationTypeName) {
        this.laminationTypeName = laminationTypeName;
    }

    
    @Column(name="lamination_desc", nullable=false, length=250)
    public String getLaminationDesc() {
        return this.laminationDesc;
    }
    
    public void setLaminationDesc(String laminationDesc) {
        this.laminationDesc = laminationDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lamination_added_date", nullable=false, length=10)
    public Date getLaminationAddedDate() {
        return this.laminationAddedDate;
    }
    
    public void setLaminationAddedDate(Date laminationAddedDate) {
        this.laminationAddedDate = laminationAddedDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblLaminationType")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


