package com.main.pojo;
// Generated Nov 26, 2016 10:29:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblOrdertype generated by hbm2java
 */
@Entity
@Table(name="tbl_ordertype"
    ,catalog="offsetmanager"
)
public class TblOrdertype  implements java.io.Serializable {


     private Integer ordertypeId;
     private String ordertypeName;
     private char isActive;
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblOrdertype() {
    }

	
    public TblOrdertype(String ordertypeName, char isActive) {
        this.ordertypeName = ordertypeName;
        this.isActive = isActive;
    }
    public TblOrdertype(String ordertypeName, char isActive, Set<TblOrder> tblOrders) {
       this.ordertypeName = ordertypeName;
       this.isActive = isActive;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ordertype_id", unique=true, nullable=false)
    public Integer getOrdertypeId() {
        return this.ordertypeId;
    }
    
    public void setOrdertypeId(Integer ordertypeId) {
        this.ordertypeId = ordertypeId;
    }

    
    @Column(name="ordertype_name", nullable=false, length=100)
    public String getOrdertypeName() {
        return this.ordertypeName;
    }
    
    public void setOrdertypeName(String ordertypeName) {
        this.ordertypeName = ordertypeName;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="tblOrdertype")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


