package com.main.pojo;
// Generated 3 Nov, 2016 4:21:05 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOrder generated by hbm2java
 */
@Entity
@Table(name = "tbl_order", catalog = "offsetmanager"
)
public class TblOrder implements java.io.Serializable {

    private Integer orderId;
    private TblCardType tblCardType;
    private TblClient tblClient;
    private TblGsmsize tblGsmsize;
    private TblLaminationType tblLaminationType;
    private TblPaper tblPaper;
    private TblPostpress tblPostpress;
    private TblPrintingType tblPrintingType;
    private TblQty tblQty;
    private TblQuotation tblQuotation;
    private TblSides tblSides;
    private String comment;
    private Date requestdate;
    private String orderstatus;
    private Character isactive;
    private Set<TblOrderStatusHistory> tblOrderStatusHistories = new HashSet<TblOrderStatusHistory>(0);

    public TblOrder() {
    }

    public TblOrder(Date requestdate) {
        this.requestdate = requestdate;
    }

    public TblOrder(TblCardType tblCardType, TblClient tblClient, TblGsmsize tblGsmsize, TblLaminationType tblLaminationType, TblPaper tblPaper, TblPostpress tblPostpress, TblPrintingType tblPrintingType, TblQty tblQty, TblQuotation tblQuotation, TblSides tblSides, String comment, Date requestdate, String orderstatus, Character isactive, Set<TblOrderStatusHistory> tblOrderStatusHistories) {
        this.tblCardType = tblCardType;
        this.tblClient = tblClient;
        this.tblGsmsize = tblGsmsize;
        this.tblLaminationType = tblLaminationType;
        this.tblPaper = tblPaper;
        this.tblPostpress = tblPostpress;
        this.tblPrintingType = tblPrintingType;
        this.tblQty = tblQty;
        this.tblQuotation = tblQuotation;
        this.tblSides = tblSides;
        this.comment = comment;
        this.requestdate = requestdate;
        this.orderstatus = orderstatus;
        this.isactive = isactive;
        this.tblOrderStatusHistories = tblOrderStatusHistories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "order_id", unique = true, nullable = false)
    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "card_type_id")
    public TblCardType getTblCardType() {
        return this.tblCardType;
    }

    public void setTblCardType(TblCardType tblCardType) {
        this.tblCardType = tblCardType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public TblClient getTblClient() {
        return this.tblClient;
    }

    public void setTblClient(TblClient tblClient) {
        this.tblClient = tblClient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gsm_id")
    public TblGsmsize getTblGsmsize() {
        return this.tblGsmsize;
    }

    public void setTblGsmsize(TblGsmsize tblGsmsize) {
        this.tblGsmsize = tblGsmsize;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lamination_type_id")
    public TblLaminationType getTblLaminationType() {
        return this.tblLaminationType;
    }

    public void setTblLaminationType(TblLaminationType tblLaminationType) {
        this.tblLaminationType = tblLaminationType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "paper_id")
    public TblPaper getTblPaper() {
        return this.tblPaper;
    }

    public void setTblPaper(TblPaper tblPaper) {
        this.tblPaper = tblPaper;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "postpress_id")
    public TblPostpress getTblPostpress() {
        return this.tblPostpress;
    }

    public void setTblPostpress(TblPostpress tblPostpress) {
        this.tblPostpress = tblPostpress;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "printing_type_id")
    public TblPrintingType getTblPrintingType() {
        return this.tblPrintingType;
    }

    public void setTblPrintingType(TblPrintingType tblPrintingType) {
        this.tblPrintingType = tblPrintingType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "qty_id")
    public TblQty getTblQty() {
        return this.tblQty;
    }

    public void setTblQty(TblQty tblQty) {
        this.tblQty = tblQty;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quotation_id")
    public TblQuotation getTblQuotation() {
        return this.tblQuotation;
    }

    public void setTblQuotation(TblQuotation tblQuotation) {
        this.tblQuotation = tblQuotation;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "side_id")
    public TblSides getTblSides() {
        return this.tblSides;
    }

    public void setTblSides(TblSides tblSides) {
        this.tblSides = tblSides;
    }

    @Column(name = "comment", length = 65535)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "requestdate", nullable = false, length = 10)
    public Date getRequestdate() {
        return this.requestdate;
    }

    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }

    @Column(name = "orderstatus", length = 10)
    public String getOrderstatus() {
        return this.orderstatus;
    }

    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus;
    }

    @Column(name = "isactive", length = 1)
    public Character getIsactive() {
        return this.isactive;
    }

    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tblOrder")
    public Set<TblOrderStatusHistory> getTblOrderStatusHistories() {
        return this.tblOrderStatusHistories;
    }

    public void setTblOrderStatusHistories(Set<TblOrderStatusHistory> tblOrderStatusHistories) {
        this.tblOrderStatusHistories = tblOrderStatusHistories;
    }

}
