package com.main.pojo;
// Generated Nov 14, 2016 5:08:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOrderStatusHistory generated by hbm2java
 */
@Entity
@Table(name="tbl_order_status_history"
    ,catalog="offsetmanager"
)
public class TblOrderStatusHistory  implements java.io.Serializable {


     private Integer id;
     private TblOrder tblOrder;
     private String orderstatus;
     private Date createdate;
     private Date modifydate;

    public TblOrderStatusHistory() {
    }

    public TblOrderStatusHistory(TblOrder tblOrder, String orderstatus, Date createdate, Date modifydate) {
       this.tblOrder = tblOrder;
       this.orderstatus = orderstatus;
       this.createdate = createdate;
       this.modifydate = modifydate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id")
    public TblOrder getTblOrder() {
        return this.tblOrder;
    }
    
    public void setTblOrder(TblOrder tblOrder) {
        this.tblOrder = tblOrder;
    }

    
    @Column(name="orderstatus", length=10)
    public String getOrderstatus() {
        return this.orderstatus;
    }
    
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdate", length=10)
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modifydate", length=10)
    public Date getModifydate() {
        return this.modifydate;
    }
    
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }




}


