package com.main.pojo;
// Generated 3 Nov, 2016 4:21:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPrintingType generated by hbm2java
 */
@Entity
@Table(name="tbl_printing_type"
    ,catalog="offsetmanager"
)
public class TblPrintingType  implements java.io.Serializable {


     private Integer printingTypeId;
     private String printingTypeName;
     private Date ptAddedDate;
     private char isActive;
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblPrintingType() {
    }

	
    public TblPrintingType(String printingTypeName, Date ptAddedDate, char isActive) {
        this.printingTypeName = printingTypeName;
        this.ptAddedDate = ptAddedDate;
        this.isActive = isActive;
    }
    public TblPrintingType(String printingTypeName, Date ptAddedDate, char isActive, Set<TblOrder> tblOrders) {
       this.printingTypeName = printingTypeName;
       this.ptAddedDate = ptAddedDate;
       this.isActive = isActive;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="printing_type_id", unique=true, nullable=false)
    public Integer getPrintingTypeId() {
        return this.printingTypeId;
    }
    
    public void setPrintingTypeId(Integer printingTypeId) {
        this.printingTypeId = printingTypeId;
    }

    
    @Column(name="printing_type_name", nullable=false)
    public String getPrintingTypeName() {
        return this.printingTypeName;
    }
    
    public void setPrintingTypeName(String printingTypeName) {
        this.printingTypeName = printingTypeName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pt_added_date", nullable=false, length=10)
    public Date getPtAddedDate() {
        return this.ptAddedDate;
    }
    
    public void setPtAddedDate(Date ptAddedDate) {
        this.ptAddedDate = ptAddedDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblPrintingType")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


