package com.main.pojo;
// Generated 3 Nov, 2016 4:21:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPostpress generated by hbm2java
 */
@Entity
@Table(name="tbl_postpress"
    ,catalog="offsetmanager"
)
public class TblPostpress  implements java.io.Serializable {


     private Integer postpressId;
     private String postpressName;
     private String postpressDesc;
     private Date postpressAddedDate;
     private char isActive;
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblPostpress() {
    }

	
    public TblPostpress(String postpressName, String postpressDesc, Date postpressAddedDate, char isActive) {
        this.postpressName = postpressName;
        this.postpressDesc = postpressDesc;
        this.postpressAddedDate = postpressAddedDate;
        this.isActive = isActive;
    }
    public TblPostpress(String postpressName, String postpressDesc, Date postpressAddedDate, char isActive, Set<TblOrder> tblOrders) {
       this.postpressName = postpressName;
       this.postpressDesc = postpressDesc;
       this.postpressAddedDate = postpressAddedDate;
       this.isActive = isActive;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="postpress_id", unique=true, nullable=false)
    public Integer getPostpressId() {
        return this.postpressId;
    }
    
    public void setPostpressId(Integer postpressId) {
        this.postpressId = postpressId;
    }

    
    @Column(name="postpress_name", nullable=false, length=30)
    public String getPostpressName() {
        return this.postpressName;
    }
    
    public void setPostpressName(String postpressName) {
        this.postpressName = postpressName;
    }

    
    @Column(name="postpress_desc", nullable=false, length=65535)
    public String getPostpressDesc() {
        return this.postpressDesc;
    }
    
    public void setPostpressDesc(String postpressDesc) {
        this.postpressDesc = postpressDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="postpress_added_date", nullable=false, length=10)
    public Date getPostpressAddedDate() {
        return this.postpressAddedDate;
    }
    
    public void setPostpressAddedDate(Date postpressAddedDate) {
        this.postpressAddedDate = postpressAddedDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblPostpress")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


