package com.main.pojo;
// Generated Nov 24, 2016 11:14:27 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblQuotation generated by hbm2java
 */
@Entity
@Table(name="tbl_quotation"
    ,catalog="offsetmanager"
)
public class TblQuotation  implements java.io.Serializable {


     private Integer quotationId;
     private TblClient tblClient;
     private String quotationDesc;
     private Date quotationAddedDate;
     private Date quotationUpdateDate;
     private String readStatus;
     private char isActive;
     private Set<TblQuotationhistory> tblQuotationhistories = new HashSet<TblQuotationhistory>(0);
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblQuotation() {
    }

	
    public TblQuotation(Date quotationAddedDate, Date quotationUpdateDate, String readStatus, char isActive) {
        this.quotationAddedDate = quotationAddedDate;
        this.quotationUpdateDate = quotationUpdateDate;
        this.readStatus = readStatus;
        this.isActive = isActive;
    }
    public TblQuotation(TblClient tblClient, String quotationDesc, Date quotationAddedDate, Date quotationUpdateDate, String readStatus, char isActive, Set<TblQuotationhistory> tblQuotationhistories, Set<TblOrder> tblOrders) {
       this.tblClient = tblClient;
       this.quotationDesc = quotationDesc;
       this.quotationAddedDate = quotationAddedDate;
       this.quotationUpdateDate = quotationUpdateDate;
       this.readStatus = readStatus;
       this.isActive = isActive;
       this.tblQuotationhistories = tblQuotationhistories;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="quotation_id", unique=true, nullable=false)
    public Integer getQuotationId() {
        return this.quotationId;
    }
    
    public void setQuotationId(Integer quotationId) {
        this.quotationId = quotationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id")
    public TblClient getTblClient() {
        return this.tblClient;
    }
    
    public void setTblClient(TblClient tblClient) {
        this.tblClient = tblClient;
    }

    
    @Column(name="quotation_desc", length=65535)
    public String getQuotationDesc() {
        return this.quotationDesc;
    }
    
    public void setQuotationDesc(String quotationDesc) {
        this.quotationDesc = quotationDesc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="quotation_added_date", nullable=false, length=10)
    public Date getQuotationAddedDate() {
        return this.quotationAddedDate;
    }
    
    public void setQuotationAddedDate(Date quotationAddedDate) {
        this.quotationAddedDate = quotationAddedDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="quotation_update_date", nullable=false, length=10)
    public Date getQuotationUpdateDate() {
        return this.quotationUpdateDate;
    }
    
    public void setQuotationUpdateDate(Date quotationUpdateDate) {
        this.quotationUpdateDate = quotationUpdateDate;
    }

    
    @Column(name="read_status", nullable=false, length=20)
    public String getReadStatus() {
        return this.readStatus;
    }
    
    public void setReadStatus(String readStatus) {
        this.readStatus = readStatus;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblQuotation")
    public Set<TblQuotationhistory> getTblQuotationhistories() {
        return this.tblQuotationhistories;
    }
    
    public void setTblQuotationhistories(Set<TblQuotationhistory> tblQuotationhistories) {
        this.tblQuotationhistories = tblQuotationhistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblQuotation")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


