package com.main.pojo;
// Generated 4 Nov, 2016 4:39:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblQuotationhistory generated by hbm2java
 */
@Entity
@Table(name="tbl_quotationhistory"
    ,catalog="offsetmanager"
)
public class TblQuotationhistory  implements java.io.Serializable {


     private Integer id;
     private TblQuotation tblQuotation;
     private String requestquery;
     private String replyanswer;
     private Date requestdate;
     private Date replydate;
     private String hisstatus;
     private Character isactive;

    public TblQuotationhistory() {
    }

	
    public TblQuotationhistory(Date requestdate, Date replydate) {
        this.requestdate = requestdate;
        this.replydate = replydate;
    }
    public TblQuotationhistory(TblQuotation tblQuotation, String requestquery, String replyanswer, Date requestdate, Date replydate, String hisstatus, Character isactive) {
       this.tblQuotation = tblQuotation;
       this.requestquery = requestquery;
       this.replyanswer = replyanswer;
       this.requestdate = requestdate;
       this.replydate = replydate;
       this.hisstatus = hisstatus;
       this.isactive = isactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="quotation_id")
    public TblQuotation getTblQuotation() {
        return this.tblQuotation;
    }
    
    public void setTblQuotation(TblQuotation tblQuotation) {
        this.tblQuotation = tblQuotation;
    }

    
    @Column(name="requestquery", length=65535)
    public String getRequestquery() {
        return this.requestquery;
    }
    
    public void setRequestquery(String requestquery) {
        this.requestquery = requestquery;
    }

    
    @Column(name="replyanswer", length=65535)
    public String getReplyanswer() {
        return this.replyanswer;
    }
    
    public void setReplyanswer(String replyanswer) {
        this.replyanswer = replyanswer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="requestdate", nullable=false, length=10)
    public Date getRequestdate() {
        return this.requestdate;
    }
    
    public void setRequestdate(Date requestdate) {
        this.requestdate = requestdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="replydate", nullable=false, length=10)
    public Date getReplydate() {
        return this.replydate;
    }
    
    public void setReplydate(Date replydate) {
        this.replydate = replydate;
    }

    
    @Column(name="hisstatus", length=10)
    public String getHisstatus() {
        return this.hisstatus;
    }
    
    public void setHisstatus(String hisstatus) {
        this.hisstatus = hisstatus;
    }

    
    @Column(name="isactive", length=1)
    public Character getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Character isactive) {
        this.isactive = isactive;
    }




}


