package com.main.pojo;
// Generated 3 Nov, 2016 4:21:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblSides generated by hbm2java
 */
@Entity
@Table(name="tbl_sides"
    ,catalog="offsetmanager"
)
public class TblSides  implements java.io.Serializable {


     private Integer sideId;
     private String sideName;
     private Date sideAddedDate;
     private char isActive;
     private Set<TblOrder> tblOrders = new HashSet<TblOrder>(0);

    public TblSides() {
    }

	
    public TblSides(String sideName, Date sideAddedDate, char isActive) {
        this.sideName = sideName;
        this.sideAddedDate = sideAddedDate;
        this.isActive = isActive;
    }
    public TblSides(String sideName, Date sideAddedDate, char isActive, Set<TblOrder> tblOrders) {
       this.sideName = sideName;
       this.sideAddedDate = sideAddedDate;
       this.isActive = isActive;
       this.tblOrders = tblOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="side_id", unique=true, nullable=false)
    public Integer getSideId() {
        return this.sideId;
    }
    
    public void setSideId(Integer sideId) {
        this.sideId = sideId;
    }

    
    @Column(name="side_name", nullable=false)
    public String getSideName() {
        return this.sideName;
    }
    
    public void setSideName(String sideName) {
        this.sideName = sideName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="side_added_date", nullable=false, length=10)
    public Date getSideAddedDate() {
        return this.sideAddedDate;
    }
    
    public void setSideAddedDate(Date sideAddedDate) {
        this.sideAddedDate = sideAddedDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblSides")
    public Set<TblOrder> getTblOrders() {
        return this.tblOrders;
    }
    
    public void setTblOrders(Set<TblOrder> tblOrders) {
        this.tblOrders = tblOrders;
    }




}


