package com.main.pojo;
// Generated Nov 14, 2016 5:08:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUsertype generated by hbm2java
 */
@Entity
@Table(name="tbl_usertype"
    ,catalog="offsetmanager"
)
public class TblUsertype  implements java.io.Serializable {


     private Integer usertypeId;
     private String usertype;
     private Date usertypeAddedDate;
     private char isActive;

    public TblUsertype() {
    }

    public TblUsertype(String usertype, Date usertypeAddedDate, char isActive) {
       this.usertype = usertype;
       this.usertypeAddedDate = usertypeAddedDate;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="usertype_id", unique=true, nullable=false)
    public Integer getUsertypeId() {
        return this.usertypeId;
    }
    
    public void setUsertypeId(Integer usertypeId) {
        this.usertypeId = usertypeId;
    }

    
    @Column(name="usertype", nullable=false, length=100)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="usertype_added_date", nullable=false, length=10)
    public Date getUsertypeAddedDate() {
        return this.usertypeAddedDate;
    }
    
    public void setUsertypeAddedDate(Date usertypeAddedDate) {
        this.usertypeAddedDate = usertypeAddedDate;
    }

    
    @Column(name="is_active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }




}


